//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appHorarios {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("appHorarios.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualiza las estadísticas en base a las opciones.
        /// </summary>
        internal static string msgBtnActualizar {
            get {
                return ResourceManager.GetString("msgBtnActualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancela todos los cambios y reinicia la ventana al estado inicial.
        /// </summary>
        internal static string msgBtnCancelar {
            get {
                return ResourceManager.GetString("msgBtnCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guarda el registro recién ingresado de forma temporal (hasta cerrar la ventana).
        /// </summary>
        internal static string msgBtnGuardar {
            get {
                return ResourceManager.GetString("msgBtnGuardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guarda los registros en el archivo.
        /// </summary>
        internal static string msgBtnGuardarTodo {
            get {
                return ResourceManager.GetString("msgBtnGuardarTodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habilta los campos para ingresar un nuevo registro.
        /// </summary>
        internal static string msgBtnNuevoHabilitar {
            get {
                return ResourceManager.GetString("msgBtnNuevoHabilitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pone &apos;en cero&apos; las estadísticas..
        /// </summary>
        internal static string msgBtnReiniciar {
            get {
                return ResourceManager.GetString("msgBtnReiniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habilita los campos para ingresar datos sobre el viaje en bicicleta (si lo hubo).
        /// </summary>
        internal static string msgCheckBoxHabBicicleta {
            get {
                return ResourceManager.GetString("msgCheckBoxHabBicicleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalida el tiempo de descanso (no lo tiene en cuenta para las estadísticas).
        /// </summary>
        internal static string msgCheckInvalidarDescanso {
            get {
                return ResourceManager.GetString("msgCheckInvalidarDescanso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Meses de los registros del listado (para estadísticas mensuales o acumuladas).
        /// </summary>
        internal static string msgComboMeses {
            get {
                return ResourceManager.GetString("msgComboMeses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalles adicionales del viaje en bicicleta.
        /// </summary>
        internal static string msgDetalleBicicleta {
            get {
                return ResourceManager.GetString("msgDetalleBicicleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver estadísticas desde cierto mes en adelante (elegir mes).
        /// </summary>
        internal static string msgEstadAcumulado {
            get {
                return ResourceManager.GetString("msgEstadAcumulado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver estadísticas por mes (elegir mes).
        /// </summary>
        internal static string msgEstadMensual {
            get {
                return ResourceManager.GetString("msgEstadMensual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver estadísticas totales (tomando todos los registros).
        /// </summary>
        internal static string msgEstadTotales {
            get {
                return ResourceManager.GetString("msgEstadTotales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha del registro.
        /// </summary>
        internal static string msgFechaRegistro {
            get {
                return ResourceManager.GetString("msgFechaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horario de entrada (hh:mm:ss).
        /// </summary>
        internal static string msgHorarioEntrada {
            get {
                return ResourceManager.GetString("msgHorarioEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horario de salida (hh:mm:ss).
        /// </summary>
        internal static string msgHoraSalida {
            get {
                return ResourceManager.GetString("msgHoraSalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duración del viaje de ida en bicicleta.
        /// </summary>
        internal static string msgIdaBicicleta {
            get {
                return ResourceManager.GetString("msgIdaBicicleta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Muestra el listado de los registros (por fecha).
        /// </summary>
        internal static string msgListViewRegistros {
            get {
                return ResourceManager.GetString("msgListViewRegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones o detalles adicionales del registro.
        /// </summary>
        internal static string msgObservaciones {
            get {
                return ResourceManager.GetString("msgObservaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo de duración del descanso (hh:mm:ss).
        /// </summary>
        internal static string msgTiempoDescanso {
            get {
                return ResourceManager.GetString("msgTiempoDescanso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duración del viaje de vuelta en bicicleta.
        /// </summary>
        internal static string msgVueltaBicicleta {
            get {
                return ResourceManager.GetString("msgVueltaBicicleta", resourceCulture);
            }
        }
    }
}
